# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: registry.gitlab.com/dren-tech/school-exit-room/caddy-php:9-create-docker-container

# Select what we should cache between builds
cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - pre-build
  - build
  - test

frontend_build:
  stage: pre-build
  image: node:lts
  script:
    - yarn install

composer:
  stage: pre-build
  script:
    - composer install

docker-build-caddyphp-master:
  stage: pre-build
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"/caddy-php docker
    - docker push "$CI_REGISTRY_IMAGE"/caddy-php
  only:
    - master

docker-build-caddyphp:
  stage: pre-build
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/caddy-php:$CI_COMMIT_REF_SLUG" docker
    - docker push "$CI_REGISTRY_IMAGE/caddy-php:$CI_COMMIT_REF_SLUG"
  except:
    - master

docker-build-master:
  stage: build
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"/ docker
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  stage: build
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" docker
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
#test:
#  script:
#    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
